"""Add migrate and user preferences

Revision ID: 0f925483f871
Revises: 2d9a8a5137bf
Create Date: 2025-04-01 10:58:53.339828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f925483f871'
down_revision = '2d9a8a5137bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_genres', sa.String(length=300), nullable=True))

    with op.batch_alter_table('watch_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_history', schema=None) as batch_op:
        batch_op.drop_column('rating')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('favorite_genres')

    # ### end Alembic commands ###
