"""Uptaded Movie Model

Revision ID: 1e274b468522
Revises: 63a8f987b9a6
Create Date: 2025-04-24 09:08:56.562307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e274b468522'
down_revision = '63a8f987b9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('release_date',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['tmdb_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('release_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('tmdb_id')

    # ### end Alembic commands ###
