"""Added vote_count column TVShow and Movie

Revision ID: 43b2bd9d825a
Revises: 4debf973325c
Create Date: 2025-05-02 09:46:53.693742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b2bd9d825a'
down_revision = '4debf973325c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('tv_show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tv_show', schema=None) as batch_op:
        batch_op.drop_column('vote_count')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('vote_count')

    # ### end Alembic commands ###
