"""Updated Models

Revision ID: 4debf973325c
Revises: 1e274b468522
Create Date: 2025-04-26 21:18:17.126260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4debf973325c'
down_revision = '1e274b468522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tv_show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('poster_url', sa.String(length=300), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('imdb_rating', sa.Float(), nullable=True),
    sa.Column('number_of_seasons', sa.Integer(), nullable=True),
    sa.Column('number_of_episodes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_table('user_favorite_tv_shows',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tv_show_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tv_show_id'], ['tv_show.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tv_show_id')
    )
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tv_show_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recomended_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'tv_show', ['tv_show_id'], ['id'])
        batch_op.drop_column('reccomended_at')

    with op.batch_alter_table('watch_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tv_show_id', sa.Integer(), nullable=True))
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'tv_show', ['tv_show_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('tv_show_id')

    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reccomended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('recomended_at')
        batch_op.drop_column('tv_show_id')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=True))

    op.drop_table('user_favorite_tv_shows')
    op.drop_table('tv_show')
    # ### end Alembic commands ###
