"""Remove column favorite_genres from user

Revision ID: 63a8f987b9a6
Revises: 0f925483f871
Create Date: 2025-04-01 12:40:21.448867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a8f987b9a6'
down_revision = '0f925483f871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('favorite_genres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_genres', sa.VARCHAR(length=300), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
